config/routes.rb
Rails.application.routes.draw do

 # devise_for :users, :skip => [:registrations]
 # as :user do
  #  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
   # put 'users' => 'devise/registrations#update', :as => 'user_registration'
  #end
  #devise_for :users, controllers: { sessions: 'users/sessions' }
 # devise_scope :user do
  #  get 'sign_in', to: 'devise/sessions#new'
  #end
  #get '/homes/new_user', :to => 'devise/registrations#new', :as => "new_user"
  #get 'create_new', :to => 'devise/registrations#new'
  #devise_scope :users do
   # get '/create', to: 'devise/registrations#new', as: :create
  #end
  root to: "homes#home"
  devise_scope :user do
    get 'create', to: 'devise/registrations#new'
  end


  devise_for :users
  resources :homes
  resources :stocks
  resources :units
  resources :sales
  resources :sale_items
  resources :suppliers
  resources :items
  resources :purchases
  resources :purchase_items
  resources :customers
  resources :user_profiles
  resources :logs
  resources :item_groups
resources :fiscal_years
  resources :company_profiles
  get '/setting' => 'homes#setting'
  get "/add_fields" => "sales#add_fields"
 # resources :users_admin, :controller => 'users'
  get "/users/sign_up", to: redirect('/404')
  get "/logs/new", to: redirect('/404')

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :sale
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  has_one :company_profile
  has_one :item
  has_one :purchase
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_group
  belongs_to :unit
  belongs_to :fiscal_year
  has_one :stock, inverse_of: :item, dependent: :destroy
  accepts_nested_attributes_for :stock
  validates :name, presence: true
  validates :item_code, presence: true
  validates :unit_id, presence: true
  validates :item_group_id, presence: true
  validates :name, presence: true
  has_one :stock,inverse_of: :item, :dependent => :destroy
  accepts_nested_attributes_for :stock
  has_many :purchase_items
  has_many :sale_items
  def self.search(search)
    if search
     where('name LIKE ?', "%#{search}%")
    else
      all
    end
end
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items, :dependent => :destroy
  has_many :item_groups
  validates :name, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_items, :dependent => :destroy
  accepts_nested_attributes_for :purchase_items, :allow_destroy => true
  belongs_to :supplier
  belongs_to :fiscal_year
  has_one :company_profile

end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item

end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_items, :dependent => :destroy
  accepts_nested_attributes_for :sale_items, :allow_destroy => true
  belongs_to :customer
  has_one :company_profile
  belongs_to :fiscal_year
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :sale, required: false
  belongs_to :item
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item, inverse_of: :stock
end

app/models/supplier.rb
class Supplier < ApplicationRecord
has_many :purchases
  validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :items, :dependent => :destroy
  validates :name, presence: true
  validates :print_name, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 # attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :middle_name, :last_name
  has_many :logs, :dependent => :destroy
end

app/controllers/item_groups_controller.rb
class ItemGroupsController < ApplicationController
    def edit
      @item_group = ItemGroup.find(params[:id])
    end

    def show
      @item_group = ItemGroup.find(params[:id])
    end

    def index
      @page = params[:page] || 1
      @item_group = ItemGroup.paginate(:page => params[:page], :per_page =>10)
    end

    def update
      @item_group = ItemGroup.find(params[:id])
     if @item_group.update(item_group_param)
       @log = Log.create(description: "Edited item group "+ @item_group.name, user: current_user )
       flash[:success] = "Item group edited successfully !"
      redirect_to "/item_groups"
     else
       render 'edit'
       end

    end

    def destroy

      @item_group = ItemGroup.find(params[:id])
      @log = Log.create(description: "Deleted item group"+ @item_group.name, user: current_user )
      @item_group.destroy
      flash[:success] = "Item group deleted successfully !!"
      redirect_to "/item_groups"
    end

    def new
      @item_group = ItemGroup.new
    end

    def create
      @item_group= ItemGroup.new(item_group_param)
      if @item_group.save
        @log = Log.create(description: "Added new item group "+ @item_group.name, user: current_user )
        flash[:success] = "Item group added successfully !!"
        redirect_to "/item_groups"
      else
        render 'new'
      end
    end

    private
    def item_group_param
      params.require(:item_group).permit(:name, :parent_id, :description)
    end
    
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/item_groups_helper.rb
module ItemGroupsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/item_groups/_form.html.erb
 <%= form_for @item_group, :html => {:class=>"form-horizontal"} do |f| %>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Name <label class="compulsary">*</label></label></div>
            <div class="col-md-9">
              <%= f.text_field :name, :class=>"form-control",:placeholder=>"Group Name" %></div>
          </div>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Parent Id</label></div>
            <div class="col-md-9">
              <%= f.collection_select :parent_id, ItemGroup.order(:name),:id, :name, {prompt: "Select Item Group"}, {class:"form-control"} %></div>
          </div>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Description</label></div>
            <div class="col-md-9">
              <%= f.text_area :description, :class=>"form-control",:placeholder=>"Write short description about your group" %></div>
          </div>
          <div class="row">
            <div class="col-sm-offset-3 col-sm-3">
              <button class="btn btn-primary btn-block btn-lg" type="submit">Submit
              </button></div>
          </div>
      <% end %>

app/views/item_groups/create.html.erb
<h1>ItemGroups#create</h1>
<p>Find me in app/views/item_groups/create.html.erb</p>

app/views/item_groups/destroy.html.erb
<h1>ItemGroups#destroy</h1>
<p>Find me in app/views/item_groups/destroy.html.erb</p>

app/views/item_groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3><i class="fa fa-pencil-square-o fa-fw"></i>Edit Item Group</h3><hr>
      <div class="row">
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li><a href="/items_groups">Item Groups</a></li>
            <li>Edit Item Groups</li>
          </ol></div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <% if @item_group.errors.any? %>
              <div class="panel panel-danger">
                <div class="panel-heading">
                  <h5 class="panel-title">
                    <%= pluralize(@item_group.errors.count,"error") %> occured</h5>
                </div>
                <div class="panel-body">
                  <ul>
                    <% @item_group.errors.full_messages.each do |e| %>
                        <li>
                          <%= e %>
                        </li>
                    <% end %>
                  </ul></div></div>
          <% end %>
        </div>
      </div>
      <%= render "form" %></div></div></div>

app/views/item_groups/index.html.erb
<div class="container">
  <h3>List All Item Groups</h3><hr>
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li>Item Groups</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-sm-12">
    <a href="/item_groups/new" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> Add New
    </a></div>
  </div><br>
  <% if @item_group.count == 0 %>
      <div class="row">
        <div class="col-sm-12">
          <h3>No records !!</h3></div></div><hr>
  <% else %>

  <div class="row">
    <table class="table table-hover table-responsive">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Parent Id</th>
        <th>Description</th>
        <th>Actions</th>
      </tr></thead>
      <% @item_group.each_with_index do |setting,i| %>
          <tbody>
          <tr>
            <td><%= (@page.to_i - 1) *5+i+1 %></td>
            <td><%= setting.name %></td>
            <td><%= setting.parent_id %></td>
            <td><%= setting.description %></td>
            <td><a title="View details" href="<%= item_group_path(setting) %>" data-toggle="tooltip" data-placement="right" class="a"><i class="fa fa-eye"  aria-hidden="true"></i></a>
              <a title="Edit Details" href="<%= edit_item_group_path(setting) %>" data-toggle="tooltip" data-placement="right" class="a" ><i class="fa fa-pencil-square-o"  aria-hidden="true"></i></a>
              <a title="Delete" data-method="delete" href="<%= item_group_path(setting) %>" data-confirm="Are you sure?" data-toggle="tooltip" data-placement="right" class="a" ><i class="fa fa-trash-o"  aria-hidden="true"></i></a></td>
          </tr></tbody>
      <% end %>
    </table>
    <% end  %>

    <%= will_paginate @item_group, renderer: BootstrapPagination::Rails %>
  </div>
</div>
<script>
  $(document).on("ready page:change", function() {
    $('.a').tooltip();
  });
</script>

app/views/item_groups/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h3><i class="fa fa-plus fa-fw"></i>Add Item Group</h3><hr>
    <div class="row">
      <div class="col-sm-12">
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li><a href="/item_groups">Item Groups</a></li>
          <li>Add Item Group</li>
        </ol></div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <% if @item_group.errors.any? %>
            <div class="panel panel-danger">
              <div class="panel-heading">
                <h5 class="panel-title">
                  <%= pluralize(@item_group.errors.count,"error") %> occured</h5>
              </div>
              <div class="panel-body">
                <ul>
                  <% @item_group.errors.full_messages.each do |e| %>
                      <li>
                        <%= e %>
                      </li>
                  <% end %>
                </ul></div></div>
        <% end %>
      </div>
    </div>
    <%= render "form" %>
  </div>
</div>
</div>

app/views/item_groups/show.html.erb
<style>
  .thumbnail{
    margin: 0 auto;
  }
</style>

<div class="container ">
  <div class="row fixed">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <br>
    <div class="row f1">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <table class="table table-responsive table-hover">
          <tbody>
          <tr>
            <td><strong>Name : </strong><%= @item_group.name %></td></tr>
          <tr> <td><strong>Parent id: </strong><%= @item_group.parent_id %></td></tr>
          <tr> <td><strong>Description: </strong><%= @item_group.description %></td></tr>

          </tbody>
        </table></div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-2">
        <a title="Edit details" href="<%= edit_item_group_path(@item_group) %>" class="btn btn-primary">Edit Details</a></div>
      <div class="col-md-2">
        <a title="View All" href="<%= item_groups_path %>" class="btn btn-primary">View All</a><br><br>
      </div>
    </div>
  </div>
</div>

app/views/item_groups/update.html.erb
<h1>ItemGroups#update</h1>
<p>Find me in app/views/item_groups/update.html.erb</p>