config/routes.rb
Rails.application.routes.draw do

 # devise_for :users, :skip => [:registrations]
 # as :user do
  #  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
   # put 'users' => 'devise/registrations#update', :as => 'user_registration'
  #end
  #devise_for :users, controllers: { sessions: 'users/sessions' }
 # devise_scope :user do
  #  get 'sign_in', to: 'devise/sessions#new'
  #end
  #get '/homes/new_user', :to => 'devise/registrations#new', :as => "new_user"
  #get 'create_new', :to => 'devise/registrations#new'
  #devise_scope :users do
   # get '/create', to: 'devise/registrations#new', as: :create
  #end
  root to: "homes#home"
  devise_scope :user do
    get 'create', to: 'devise/registrations#new'
  end


  devise_for :users
  resources :homes
  resources :stocks
  resources :units
  resources :sales
  resources :sale_items
  resources :suppliers
  resources :items
  resources :purchases
  resources :purchase_items
  resources :customers
  resources :user_profiles
  resources :logs
  resources :item_groups
resources :fiscal_years
  resources :company_profiles
  get '/setting' => 'homes#setting'
  get "/add_fields" => "sales#add_fields"
 # resources :users_admin, :controller => 'users'
  get "/users/sign_up", to: redirect('/404')
  get "/logs/new", to: redirect('/404')

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :sale
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  has_one :company_profile
  has_one :item
  has_one :purchase
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_group
  belongs_to :unit
  belongs_to :fiscal_year
  has_one :stock, inverse_of: :item, dependent: :destroy
  accepts_nested_attributes_for :stock
  validates :name, presence: true
  validates :item_code, presence: true
  validates :unit_id, presence: true
  validates :item_group_id, presence: true
  validates :name, presence: true
  has_one :stock,inverse_of: :item, :dependent => :destroy
  accepts_nested_attributes_for :stock
  has_many :purchase_items
  has_many :sale_items
  def self.search(search)
    if search
     where('name LIKE ?', "%#{search}%")
    else
      all
    end
end
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items, :dependent => :destroy
  has_many :item_groups
  validates :name, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_items, :dependent => :destroy
  accepts_nested_attributes_for :purchase_items, :allow_destroy => true
  belongs_to :supplier
  belongs_to :fiscal_year
  has_one :company_profile

end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item

end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_items, :dependent => :destroy
  accepts_nested_attributes_for :sale_items, :allow_destroy => true
  belongs_to :customer
  has_one :company_profile
  belongs_to :fiscal_year
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :sale, required: false
  belongs_to :item
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item, inverse_of: :stock
end

app/models/supplier.rb
class Supplier < ApplicationRecord
has_many :purchases
  validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :items, :dependent => :destroy
  validates :name, presence: true
  validates :print_name, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 # attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :middle_name, :last_name
  has_many :logs, :dependent => :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def edit
    @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
  end

  def index

  #  @items = Item.order(:name).where("name like ?", "%#{params[:term]}%")
  #  render json: @items.map(&:name)
    @page = params[:page] || 1
    @item = Item.paginate(:page => params[:page], :per_page =>10)
    @company_profile = CompanyProfile.paginate(:page => params[:page], :per_page => 10)
  end

  def update
    @item = Item.find(params[:id])
   if @item.update(item_param)
     @log = Log.create(description: "Edited a item "+ @item.name, user: current_user )
     flash[:success]= "Item edited successfully !!"
    redirect_to '/items'
   else
     render 'edit'
     end

  end


  def new
    @item = Item.new
    @item.build_stock
  end

  def create
    @item= Item.new(item_param)
    @company_profile = CompanyProfile.first
    @item.fiscal_year = @company_profile.fiscal_year
    if @item.save
      @log = Log.create(description: "Added new item "+ @item.name, user: current_user )
      flash[:success] = "Item added successfully !!"
      redirect_to '/items/new'
    else
      render 'new'
    end
  end

  def destroy

    @item = Item.find(params[:id])
    @log = Log.create(description: "Deleted an item "+ @item.name, user: current_user )
    @item.destroy
    flash[:success] = "Record Deleted !!"
    redirect_to "/items"

  end

  private
  def item_param
    params.require(:item).permit(:name, :unit_id, :item_code, :item_group_id, :description,:current_fiscal_year_id, stock_attributes: [:item_id,
    :quantity, :unit_price, :est_sell_price, :_destroy])
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
 <%= form_for @item, :html => {:class=>"form-horizontal"} do |f| %>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Item Code <label class="compulsary">*</label></label></div>
            <div class="col-md-9">
              <%= f.text_field :item_code, :class=>"form-control",:placeholder=>"Items Code" %></div>
          </div>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label"> Name  <label class="compulsary">*</label></label></div>
            <div class="col-md-9">
              <%= f.text_field :name, :class=>"form-control",:placeholder=>"Item Name" %></div>
          </div>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Unit  <label class="compulsary">*</label></label></div>
            <div class="col-md-9">
              <%= f.collection_select :unit_id, Unit.all,:id,:name, {prompt:" Select Unit"}, {class: "form-control"} %>
          </div></div>

          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Item Group <label class="compulsary">*</label></label></div>
            <div class="col-md-9">
              <%= f.collection_select :item_group_id, ItemGroup.all,:id,:name, {prompt:" Select category"}, {class: "form-control"} %>
          </div></div>
          <div class="form-group">
            <div class="col-md-3">
              <label class="control-label">Description</label></div>
            <div class="col-md-9">
              <%= f.text_area :description, :class => "form-control",:placeholder =>"Description" %></div>
          </div>

     <%= f.fields_for :stock do |s| %>
         <div class="form-group">
           <div class="col-md-3">
             <label class="control-label">Quantity <label class="compulsary">*</label></label>
           </div>
           <div class="col-md-9">
             <%= s.text_field :quantity,:class=>"form-control", :placeholder => "Quantity" %>
           </div>
         </div>

       <div class="form-group">
         <div class="col-md-3">
           <label for="" class="control-label">Unit Price <label class="compulsary">*</label></label>
         </div>
         <div class="col-md-9">
           <%= s.text_field :unit_price, :class=>"form-control", :placeholder =>"Unit Price" %>
         </div>
       </div>
         <div class="form-group">
           <div class="col-md-3">

         <label for="" class="control-label">Est. Sell Price <label class="compulsary">*</label></label></div>
           <div class="col-md-9">
         <%= s.text_field :est_sell_price, :class => "form-control", :placeholder => "Estimated Sell Price" %></div>
           </div>
     <% end %>
          <div class="row">
            <div class="col-sm-offset-3 col-sm-3">
              <button class="btn btn-primary btn-block btn-lg" type="submit">Submit
              </button></div>
          </div>
      <% end %><br><br>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3><i class="fa fa-pencil-square-o fa-fw"></i>Edit Item</h3><hr>
      <div class="row">
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li><a href="/items">Items</a></li>
            <li>Edit</li>
          </ol></div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <% if @item.errors.any? %>
              <div class="panel panel-danger">
                <div class="panel-heading">
                  <h5 class="panel-title">
                    <%= pluralize(@item.errors.count,"error") %> occured</h5>
                </div>
                <div class="panel-body">
                  <ul>
                    <% @item.errors.full_messages.each do |e| %>
                        <li>
                          <%= e %>
                        </li>
                    <% end %>
                  </ul></div></div>
          <% end %>
        </div>
      </div>
      <%= render "form" %></div></div>

app/views/items/index.html.erb
<div class="container">
  <h3>List All Items</h3><hr>
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li>Items</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <a href="/company_profiles/8/edit" title="Click to change current fiscal year" data-toggle="tooltip" class="text-success">
        <div class="col-sm-12">
          <% @company_profile.each_with_index do |c|  %>
              <h4>Current Fiscal Year : <%= c.fiscal_year.name %></h4>
          <% end %>
        </div></a>
    </div>
    <div class="col-md-3 pull-right">
      <a class="btn btn-primary pull-right" href="<%= new_item_path %>"><span><i class="fa fa-plus fa-fw">&nbsp;</i></span>
        Add New</a>
    </div>
  </div>

  </div>
<br>
  <div class="row">
    <div class="col-sm-12">
    <table class="table table-hover table-responsive">
      <thead>
      <tr>
        <th>S.N.</th>
        <th>Name</th>
        <th>Unit</th>
        <th>Item Group</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Est. Sell Price</th>
        <th>Description</th>
        <th>Actions</th>
      </tr></thead>
      <% @item.each_with_index  do |item,i| %>
          <tbody>
          <tr>
            <td><%= (@page.to_i - 1) *5+i+1 %></td>
            <td><%= item.name %></td>
            <td><%= item.unit.name %></td>
            <td><%= item.item_group.name %></td>
            <td><%= item.stock.quantity %></td>
            <td><%= item.stock.unit_price %></td>
            <td><%= item.stock.est_sell_price %></td>
            <td><%= item.description %></td>
            <td><a title="View details" href="<%= item_path(item) %>" data-toggle="tooltip" data-placement="right" class="a"><i class="fa fa-eye"  aria-hidden="true"></i></a>
              <a title="Edit Details" href="<%= edit_item_path(item) %>" data-toggle="tooltip" data-placement="right" class="a" ><i class="fa fa-pencil-square-o"  aria-hidden="true"></i></a>
              <a title="Delete" data-method="delete" href="<%= item_path(item) %>" data-confirm="Are you sure?" data-toggle="tooltip" data-placement="right" class="a" ><i class="fa fa-trash-o"  aria-hidden="true" ></i></a></td>

          </tr></tbody>
      <% end %>
    </table>

    <%= will_paginate @item, renderer: BootstrapPagination::Rails %>
  </div></div>
</div>
<script>
  $(document).on("ready page:change", function() {
    $('.a').tooltip();
  });
</script>

app/views/items/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h3><i class="fa fa-plus fa-fw"></i>Add Item</h3><hr>
    <div class="row">
      <div class="col-sm-12">
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li><a href="/items">Items</a></li>
          <li>New</li>
        </ol></div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <% if @item.errors.any? %>

            <div class="panel panel-danger">
              <div class="panel-heading">
                <h5 class="panel-title">
                <%= pluralize(@item.errors.count,"error") %> occured</h5>
              </div>
              <div class="panel-body">
              <ul>
                <% @item.errors.full_messages.each do |e| %>
                    <li>
                      <%= e %>
                    </li>
                <% end %>
              </ul></div></div>
                    <% end %>
      </div>
    </div>
    <%= render "form" %>

  </div></div>

app/views/items/show.html.erb
<div class="container ">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %></div></div>
  <br>

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3>Show Item</h3><hr>
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="/items">Items</a></li>
        <li>Show</li>
      </ol>
    </div></div>
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <table class="table table-responsive table-hover">
        <tbody>
        <tr> <td><strong>Item Code : </strong><%= @item.item_code %></td></tr>
        <tr><td><strong>Name : </strong><%= @item.name %></td></tr>
        <tr> <td><strong>Unit : </strong><%= @item.unit.name %></td></tr>
        <tr> <td><strong>Item Group : </strong><%= @item.item_group.name %></td></tr>
        <tr> <td><strong>Fiscal Year : </strong><%= @item.fiscal_year.name %></td></tr>
        <tr> <td><strong>Description : </strong><%= @item.description %></td></tr>

        </tbody>
      </table></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-offset-3 col-md-2">
      <a title="Edit details" href="<%= edit_item_path(@item) %>" class="btn btn-primary"><i class="fa fa-pencil fa-fw"></i>Edit Details</a></div>
    <div class="col-md-2">
      <a title="View All" href="<%= items_path %>" class="btn btn-primary"><i class="fa fa-eye fa-fw"></i>View All</a><br><br>
    </div>
  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>