config/routes.rb
Rails.application.routes.draw do

 # devise_for :users, :skip => [:registrations]
 # as :user do
  #  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
   # put 'users' => 'devise/registrations#update', :as => 'user_registration'
  #end
  #devise_for :users, controllers: { sessions: 'users/sessions' }
 # devise_scope :user do
  #  get 'sign_in', to: 'devise/sessions#new'
  #end
  #get '/homes/new_user', :to => 'devise/registrations#new', :as => "new_user"
  #get 'create_new', :to => 'devise/registrations#new'
  #devise_scope :users do
   # get '/create', to: 'devise/registrations#new', as: :create
  #end
  root to: "homes#home"
  devise_scope :user do
    get 'create', to: 'devise/registrations#new'
  end


  devise_for :users
  resources :homes
  resources :stocks
  resources :units
  resources :sales
  resources :sale_items
  resources :suppliers
  resources :items
  resources :purchases
  resources :purchase_items
  resources :customers
  resources :user_profiles
  resources :logs
  resources :item_groups
resources :fiscal_years
  resources :company_profiles
  get '/setting' => 'homes#setting'
  get "/add_fields" => "sales#add_fields"
 # resources :users_admin, :controller => 'users'
  get "/users/sign_up", to: redirect('/404')
  get "/logs/new", to: redirect('/404')

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :sale
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  has_one :company_profile
  has_one :item
  has_one :purchase
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_group
  belongs_to :unit
  belongs_to :fiscal_year
  has_one :stock, inverse_of: :item, dependent: :destroy
  accepts_nested_attributes_for :stock
  validates :name, presence: true
  validates :item_code, presence: true
  validates :unit_id, presence: true
  validates :item_group_id, presence: true
  validates :name, presence: true
  has_one :stock,inverse_of: :item, :dependent => :destroy
  accepts_nested_attributes_for :stock
  has_many :purchase_items
  has_many :sale_items
  def self.search(search)
    if search
     where('name LIKE ?', "%#{search}%")
    else
      all
    end
end
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items, :dependent => :destroy
  has_many :item_groups
  validates :name, presence: true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_many :purchase_items, :dependent => :destroy
  accepts_nested_attributes_for :purchase_items, :allow_destroy => true
  belongs_to :supplier
  belongs_to :fiscal_year
  has_one :company_profile

end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :purchase, required: false
  belongs_to :item

end

app/models/sale.rb
class Sale < ApplicationRecord
  has_many :sale_items, :dependent => :destroy
  accepts_nested_attributes_for :sale_items, :allow_destroy => true
  belongs_to :customer
  has_one :company_profile
  belongs_to :fiscal_year
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :sale, required: false
  belongs_to :item
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item, inverse_of: :stock
end

app/models/supplier.rb
class Supplier < ApplicationRecord
has_many :purchases
  validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :items, :dependent => :destroy
  validates :name, presence: true
  validates :print_name, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 # attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :middle_name, :last_name
  has_many :logs, :dependent => :destroy
end

app/controllers/fiscal_years_controller.rb
class FiscalYearsController < ApplicationController
    def edit
      @fiscal_year = FiscalYear.find(params[:id])
    end

    def show
      @fiscal_year = FiscalYear.find(params[:id])
    end

    def index
      @page = params[:page] || 1
      @company_profile = CompanyProfile.first
      @fiscal_years = FiscalYear.paginate(:page => params[:page], :per_page =>5)
    end

    def update
      @fiscal_year = FiscalYear.find(params[:id])
      if @fiscal_year.update(fiscal_year_param)
        @log = Log.create(description: "Edited fiscal year "+ @fiscal_year.name, user: current_user )
        flash[:success] = "Fiscal years edited successfuly !!"
      redirect_to "/fiscal_years"
      else
        render 'edit'
        end

    end

    def destroy
      @fiscal_year = FiscalYear.find(params[:id])
      @log = Log.create(description: "Deleted fiscal year "+ @fiscal_year.name, user: current_user )
      @fiscal_year.destroy
      flash[:success] = "Record deleted !!"
      redirect_to "/fiscal_years"

    end

    def new
      @fiscal_year = FiscalYear.new
    end

    def create
      @fiscal_year= FiscalYear.new(fiscal_year_param)
      if @fiscal_year.save
        @log = Log.create(description: "Added new fiscal year "+ @fiscal_year.name, user: current_user )
        flash[:success] = "Fiscal year added successfully !!"
        redirect_to "/fiscal_years"
      else
        render 'new'
      end
    end

    private
    def fiscal_year_param
      params.require(:fiscal_year).permit(:name, :start_date, :end_date)
    end
end

app/helpers/fiscal_years_helper.rb
module FiscalYearsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fiscal_years/_form.html.erb
<%= form_for @fiscal_year, :html => {:class=>"form-horizontal"} do |f| %>
    <div class="form-group">
      <div class="col-md-3">
        <label class="control-label">Name *</label></div>
      <div class="col-md-9">
        <%= f.text_field :name, :class=>"form-control",:placeholder=>"Fiscal Year Name" %></div>
    </div>
    <div class="form-group">
      <div class="col-md-3">
        <label class="control-label">Start Date *</label></div>
      <div class="col-md-9">
        <div class="input-group">

          <%= f.text_field :start_date, :class=>"form-control a1 datepicker" %>
          <span class="input-group-addon d1"><i class="fa fa-calendar" aria-hidden="true"></i></span>
        </div></div>
      </div>
    <div class="form-group">
      <div class="col-md-3">
        <label class="control-label">End Date *</label></div>
      <div class="col-md-9">
        <div class="input-group">

          <%= f.text_field :end_date, :class=>"form-control a1 datepicker", "data-provide" => 'datepicker' %>
          <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
        </div></div>
    </div>
    <div class="row">
      <div class="col-sm-offset-3 col-sm-3">
        <button class="btn btn-primary btn-block btn-lg" type="submit">Submit
        </button></div>
    </div>
<% end %>
<script src="datepicker.css"></script>
<script src="bootstrap-datepicker.js"></script>
<script>
  $('.datepicker').datepicker({
    format: "yyyy/mm/dd",
  }).on('changeDate', function(e){
    $(this).datepicker('hide');
  });
</script>

app/views/fiscal_years/edit.html.erb
<div class="container">



  <% if @fiscal_year.errors.any? %>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h5 class="panel-title">
            <%= pluralize(@fiscal_year.errors.count,"error") %> occured</h5>
        </div>
        <div class="panel-body">
          <ul>
            <% @fiscal_year.errors.full_messages.each do |e| %>
                <li>
                  <%= e %>
                </li>
            <% end %>
          </ul></div></div>
  <% end %>

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3><i class="fa fa-pencil-square-o fa-fw"></i> Edit Fiscal Year</h3><hr>
      <div class="row">
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li><a href="/fiscal_years">Fiscal Years</a></li>
            <li>Edit</li>
          </ol></div>
      </div>
      <%= render "form" %></div></div></div>

app/views/fiscal_years/index.html.erb
<div class="container">
  <h3>List All Fiscal Years</h3><hr>
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li>Fiscal Years</li>
    </ol>
  </div>
  <div class="row">
    <a class="btn btn-primary btn1" href="fiscal_years/new"><i class="fa fa-plus-circle" aria-hidden="true"> Add New </i>
    </a>
  </div><br>
  <div class="row">
    <div class="col-sm-2">
      <label>Current Fiscal Year : </label>
    </div>
    <div class="col-sm-2">
      <label><%= @company_profile.fiscal_year.name %></label>
    </div>
  </div><br>

  <div class="row">
    <table class="table table-hover table-responsive">
      <thead>
      <tr>
        <th>S.N.</th>
        <th>Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Actions</th>
      </tr></thead>
      <% @fiscal_years.each_with_index do |fiscal_year,i| %>
          <tbody>
          <tr>
            <td><%= (@page.to_i - 1) *5+i+1 %></td>
            <td><%= fiscal_year.name %></td>
            <td><%= fiscal_year.start_date %></td>
            <td><%= fiscal_year.end_date %></td>
            <td><a title="View details" href="<%= fiscal_year_path(fiscal_year) %>" data-toggle="tooltip" data-placement="right" class="a"><i class="fa fa-eye"  aria-hidden="true"></i></a>
              <a title="Edit Details" href="<%= edit_fiscal_year_path(fiscal_year) %>" data-toggle="tooltip" data-placement="right" class="a" ><i class="fa fa-pencil-square-o"  aria-hidden="true"></i></a>
              <a title="Delete" data-method="delete" href="<%= fiscal_year_path(fiscal_year) %>" data-confirm="Are you sure?" data-toggle="tooltip" data-placement="right" class="a" ><i class="fa fa-trash-o"  aria-hidden="true"></i></a></td>
          </tr></tbody>
      <% end %>
    </table>

    <%= will_paginate @fiscal_year, renderer: BootstrapPagination::Rails %>
  </div>
</div>
<script>
  $(document).on("ready page:change", function() {
    $('.a').tooltip();
  });
</script>

app/views/fiscal_years/new.html.erb
<div class="container">


  <% if @fiscal_year.errors.any? %>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h5 class="panel-title">
            <%= pluralize(@fiscal_year.errors.count,"error") %> occured</h5>
        </div>
        <div class="panel-body">
          <ul>
            <% @fiscal_year.errors.full_messages.each do |e| %>
                <li>
                  <%= e %>
                </li>
            <% end %>
          </ul></div></div>
  <% end %>
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3><i class="fa fa-plus"></i> Add Fiscal Year</h3><hr>
      <div class="row">
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li><a href="/fiscal_years">Fiscal Years</a></li>
            <li>Add</li>
          </ol></div>
      </div>
      <%= render "form" %></div></div></div>

app/views/fiscal_years/show.html.erb
<div class="container ">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %></div></div>
  <br>

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <h3>Show Fiscal Year</h3><hr>
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="/fiscal_years">Fiscal Years</a></li>
        <li>Show</li>
      </ol>
    </div></div>
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <table class="table table-responsive table-hover">
        <tbody>
        <tr>
          <td><strong>Name : </strong><%= @fiscal_year.name %></td></tr>
        <tr> <td><strong>Start Date: </strong><%= @fiscal_year.start_date %></td></tr>
        <tr> <td><strong>End Date: </strong><%= @fiscal_year.end_date %></td></tr>

        </tbody>
      </table></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-offset-3 col-md-2">
      <a title="Edit details" href="<%= edit_fiscal_year_path(@fiscal_year) %>" class="btn btn-primary"><i class="fa fa-pencil fa-fw"></i>Edit Details</a></div>
    <div class="col-md-2">
      <a title="View All" href="<%= fiscal_years_path %>" class="btn btn-primary"><i class="fa fa-eye fa-fw"></i>View All</a><br><br>
    </div>
  </div>
</div>